use_frameworks!

target 'DNTimeAndDay_Example' do
  pod 'DNTimeAndDay', :path => '../'

  target 'DNTimeAndDay_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
