use_frameworks!

def standard_pods
  pod 'DNTimeAndDay', :path => '../'
 end

target 'DNTimeAndDay_Example' do
	standard_pods
end

target 'DNTimeAndDay_Tests' do
	standard_pods
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
